---
title: "DTUrtle News"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# DTUrtle 0.7.1
 - add new vignette for Tabula Muris (Mouse) data set.
 - `combine_to_matrix()`: added `cell_extension_side` parameter to choose label append or prepend.
 - `plot_dimensional_reduction()`: added functionality to plot in dimensional reduction space.
 - `plot_transcripts_view()`: safer and more specific IdeoGram track generation.
 - `plot_transcripts_view()`: improved handling of non-UCSC chromosome identifiers.
 - `run_drimseq()`: added check for matching names of counts and tx2gene.
 - `run_drimseq()`: added `subset_counts` parameter - ability to force subset the count matrix to matching tx2gene features only.
 - `plot_dtu_table()`: disable warning for server side rendering.
 - `plot_proportion_pheatmap()`: plots names are now run through `make.names()`, as all other plots.
 - `create_dtu_table()`: changed default column names and added description of column meaning.
 - extended checks for provided file paths.
 - safer BiocParallel starting and stopping.
 - made whole package documentation searchable via docsearch.
 - README: fixed typo and added link to vignettes.
 - set GenomeInfoDb as standard Imports.
 - minor improvements.

# DTUrtle 0.2.6
## Changes
- add `add_to_table` parameter to plotting functions, to add plot savepaths directly to `dtu_table`.
- `run_drimseq()`: added description of predefined filter strategies.
- `run_drimseq()`: added check if two sample groups are left after excluding unused samples.
- minor update of function documentation.
- `plot_dtu_table()`: add `min_page_length` parameter.
- `plot_dtu_table()`: slightly change icon and heading alignment.
- added conditional vignette evaluation.
- added `knitr` in Suggests for vignette building.

# DTUrtle 0.2.5
## Changes
- initial first version.
